{% raw %}
global:
  resolve_timeout: 5m
  smtp_require_tls: true
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'
  group_by: [alertname, datacenter, app]
receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#iris-notifications'
      title: '{{ '{{' }} .GroupLabels.app {{ '}}' }} detected  {{ '{{' }} .GroupLabels.alertname {{ '}}' }}'
      text: '{{ '{{' }} range .Alerts {{ '}}' }}{{ '{{' }} .Annotations.description {{ '}}' }}\n{{ '{{' }} end {{ '}}' }} '
templates: []
{% endraw %}
