---

- name: decrypt passwords
  copy:
   content: "{{ lookup('pipe', 'ansible-vault view --vault-id {{ vault_password_file }} ' + redact_path) }}"
   dest: "{{ redact_path }}"
   decrypt: yes
   mode: 0600

- name: redact passwords
  copy:
   content: "{{ lookup('file', redact_path) | redact }}"
   dest: "{{ redact_path }}"

- name: reencrypt
  command: >-
    ansible-vault encrypt --vault-id "{{ temp_vault_password_file }}" --encrypt-vault-id default "{{ redact_path }}"
